import '@/app/globals.css';
import type { Metadata } from 'next';
import { Inter, Noto_Sans_KR } from 'next/font/google';
import Navbar from '@/app/components/templates/Navbar';
import Footer from '@/app/components/templates/Footer';
import Script from 'next/script';
import type { Locales } from '@/middleware';

const inter = Inter({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

const notoSansKR = Noto_Sans_KR({
  weight: ['400', '500', '700'],
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locales };
}) {
  return (
    <html lang={lang}>
      <Script id="smartlook-api">
        {`
          window.smartlook ||
          (function (d) {
            var o = (smartlook = function () {
                o.api.push(arguments);
              }),
              h = d.getElementsByTagName("head")[0];
            var c = d.createElement("script");
            o.api = new Array();
            c.async = true;
            c.type = "text/javascript";
            c.charset = "utf-8";
            c.src = "https://web-sdk.smartlook.com/recorder.js";
            h.appendChild(c);
          })(document);
          smartlook("init", "ec3783dc608b665c4753eb3025ccf6674e73ab19", {
            region: "eu",
          });
          smartlook("record", {
            forms: true,
            numbers: true,
            ips: true,
          });
        `}
      </Script>
      <body
        className={`${
          lang === 'ko' ? notoSansKR.className : inter.className
        } flex flex-col min-h-screen`}
      >
        <Navbar locale={lang} />
        <main className="flex-1">{children}</main>
        <div className="basis-80" />
        <Footer />
      </body>
    </html>
  );
}
