name: Bug Issue Template
description: An Issue Template for Bugs
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)
      description: List of todos
      placeholder: |
        1. Step 1:
        2. Step 2:
        3. Step 3:
      value: |
        1.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ETC
      description: ETC
      placeholder: ETC
    validations:
      required: false
