name: Staging Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment: preview
    outputs:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: ziggle-frontend
      IMAGE_TAG: dev${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://stg.ziggle.gistory.me
          environment: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          mask-aws-account-id: no

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: setup environment
        run: |
          echo "${{ vars.ENV }}" >> .env.local

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ziggle-frontend
          IMAGE_TAG: dev${{ github.run_number }} # Use run number as image tag
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update GitHub Deployment Status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update GitHub Deployment Status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
  deploy:
    name: Update Git Repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: gsainfoteam/icarus-gitops
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0

      - name: Update Kubernetes Manifest
        env:
          ECR_REGISTRY: ${{ needs.build.outputs.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ needs.build.outputs.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}
        run: |
          sed -i "s|image:.*|image: $ECR_REGISTRY\/$ECR_REPOSITORY:$IMAGE_TAG|g" infoteam/service/ziggle/next.stg.yaml

      - name: Commit and Push
        env:
          ECR_REPOSITORY: ${{ needs.build.outputs.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update image $ECR_REPOSITORY:$IMAGE_TAG"
          git push -u origin master
